services:
  quant-ai-mongo-db:
    container_name: quant-ai-mongo-db
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    image: mongo:latest
    ports: [ 10000:27017 ]
    volumes: [ ../data/mongodb-data/configdb:/data/configdb, ../data/mongodb-data/db:/data/db ]
    networks: [ quant-ai-mongo-db ]

  quant-ai-timescale-db:
    container_name: quant-ai-timescale-db
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_PASSWORD=zxcasdqwe123
      - POSTGRES_DB=quant-ai
    ports: [ 10003:5432 ]
    volumes: [ ../data/timescale-data:/var/lib/postgresql/data ]
    networks: [ quant-ai-timescale-db ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  quant-ai-persistence-etl:
    container_name: quant-ai-persistence-etl
    restart: unless-stopped
    depends_on:
      quant-ai-mongo-db:
        condition: service_healthy
      quant-ai-timescale-db:
        condition: service_healthy
    build:
      context: .
      target: local
    ports: [10070:10070]
    volumes: [.:/src]
    networks: [quant-ai-persistence-middleware, quant-ai-persistence-etl, quant-ai-mongo-db, quant-ai-timescale-db]
    entrypoint: [sleep, infinity]
    init: true

networks:
  quant-ai-mongo-db:
    driver: bridge
  quant-ai-timescale-db:
    driver: bridge
  quant-ai-persistence-middleware:
    driver: bridge
  quant-ai-persistence-etl:
    driver: bridge